# Generated by Django 3.2.9 on 2021-11-23 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('sys_ID', models.AutoField(primary_key=True, serialize=False)),
                ('classification', models.CharField(max_length=25)),
                ('phone', models.CharField(blank=True, max_length=25)),
                ('mname', models.CharField(blank=True, max_length=25, verbose_name='Middle Name')),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('campusbox', models.CharField(blank=True, max_length=25, verbose_name='Campus Box')),
                ('campusroom', models.CharField(blank=True, max_length=40, verbose_name='Campus Room')),
                ('created_at', models.DateField(blank=True, null=True)),
                ('current', models.CharField(max_length=40)),
                ('preferred_name', models.CharField(max_length=40)),
                ('position', models.CharField(max_length=100)),
                ('stutype', models.CharField(max_length=40, verbose_name='Student Type')),
                ('class_level', models.CharField(max_length=40)),
                ('cardnumber', models.IntegerField(verbose_name='Card Number')),
                ('housed', models.IntegerField(blank=True)),
                ('uuid', models.CharField(max_length=8, verbose_name='HPU ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
