# Generated by Django 3.2.9 on 2021-11-23 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='position',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='preferred_name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='stutype',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Student Type'),
        ),
    ]
