# Generated by Django 3.2.9 on 2021-11-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0006_alter_person_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='campusbox',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Campus Box'),
        ),
        migrations.AlterField(
            model_name='person',
            name='campusroom',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Campus Room'),
        ),
    ]
