# Generated by Django 3.2.9 on 2021-11-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0007_auto_20211123_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='cardnumber',
            field=models.IntegerField(null=True, verbose_name='Card Number'),
        ),
    ]
