# Generated by Django 3.2.9 on 2022-01-04 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0008_alter_person_cardnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='mname',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Middle Name'),
        ),
    ]
