# Generated by Django 3.2.9 on 2022-01-04 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0010_alter_person_campusroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='classification',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
