# Generated by Django 3.2.9 on 2022-01-04 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0011_alter_person_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='mname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Middle Name'),
        ),
    ]
