# Generated by Django 3.2.9 on 2022-01-11 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0014_alter_person_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={},
        ),
        migrations.AlterField(
            model_name='person',
            name='uuid',
            field=models.IntegerField(max_length=8, verbose_name='HPU ID'),
        ),
    ]
