# Generated by Django 3.2.11 on 2022-01-13 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0016_alter_person_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='ssn',
            field=models.IntegerField(max_length=4, null=True, verbose_name='SSN Last Four'),
        ),
    ]
