# Generated by Django 3.2.11 on 2022-01-13 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0017_person_ssn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='ssn',
            field=models.CharField(max_length=4, null=True, verbose_name='SSN Last Four'),
        ),
    ]
