# Generated by Django 3.2.11 on 2022-01-13 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=75, null=True)),
                ('phone_number', models.CharField(max_length=13, null=True)),
                ('site', models.URLField(null=True)),
                ('menu', models.URLField(null=True)),
                ('hours', models.CharField(max_length=75)),
                ('image', models.ImageField(upload_to=None)),
            ],
        ),
    ]
