# Generated by Django 3.2.11 on 2022-01-13 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dining', '0002_alter_location_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='image',
            field=models.ImageField(upload_to='dining'),
        ),
    ]
